# Generated by Django 3.2.7 on 2021-09-29 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yahoo_scraping', '0002_rename_company_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='company',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Name'),
        ),
    ]
